key:
  kis_app_key: "PSwZrk7YYIoakVSkM2e0uxtcmvekby1CQlzj"
  kis_secret_key: "RUoIy7xcAUI84NKWzHCU9mldTFDArtZFeHcIkrCAaEB2US7i4Cd/cZn2brPo2nQqoPrR9kQaHVLOA9pcolTqd+17YyP6/LWTwJBHf8lW9kAVS03bzmZFggOw1MiYp7tCuFhGPz6Eke5OZWBPTJDrFdC8bQoA1noQi2XR7BLh/MDTFElQ8F0="
system:
  mode: "VIRTUAL"
