key:
  kis_app_key: "PSuMuhGACcwYPMzMRWQp7TrYWf9kSyOF85ia"
  kis_secret_key: "aprz8+WbrhDeR4lCwg0rcfTtxA5Uez43p5ai6CF6H1PZvmAarNzaI9T1jOyYEPBn6dWeskIXShA5Rws3X6XDmNmK2SGTH9Bm3eRv+pIEly0B7ZqhlY5Tm23hR2KbgirQFbVAH20jZTyEiMxPnZeX2hzK9rP55MGDZWE6zYl093CHIMI9JWk="
system:
  mode: "REAL"
